export enum ErrorMessage {
  NOT_FOUND = "NOT_FOUND",
  INVALID_HEADERS = "INVALID_HEADERS",
  INVALID_TOKEN = "INVALID_TOKEN",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  UNABLE_TO_PROCESS_ENTITY = "UNABLE_TO_PROCESS_ENTITY",
  JSON_DECODING_ERROR = "JSON_DECODING_ERROR",
  COULD_NOT_FIND_CARTS = "COULD_NOT_FIND_CARTS",
  COULD_NOT_FIND_PRODUCTS = "COULD_NOT_FIND_PRODUCTS",
}
